---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/static-golang

inputs:
- name: source
  path: gopath/src/github.com/pivotalservices/pipeline-status-resource

outputs:
- name: built-resource

params:
  STATUS_TESTING_ACCESS_KEY_ID:
  STATUS_TESTING_SECRET_ACCESS_KEY:
  STATUS_TESTING_BUCKET:
  STATUS_TESTING_REGION:

run:
  path: gopath/src/github.com/pivotalservices/pipeline-status-resource/scripts/ci
