resources:
- name: source
  type: git
  source:
    uri: {{source-git-uri}}
    private_key: {{source-git-private-key}}
    branch: {{source-git-branch}}

- name: docker-hub
  type: docker-image
  source:
    repository: {{dockerhub-repository}}
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
- name: build-resource
  public: true
  plan:
  - get: source
    trigger: true
  - task: build-binaries
    file: source/build.yml
    params:
      STATUS_TESTING_ACCESS_KEY_ID: {{s3-access-key-id}}
      STATUS_TESTING_SECRET_ACCESS_KEY: {{s3-secret-access-key}}
      STATUS_TESTING_BUCKET: {{s3-bucket}}
      STATUS_TESTING_REGION: {{s3-region}}
  - put: docker-hub
    params:
      build: built-resource
