platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
run:
  path: source/ci/tasks/runTests.sh

inputs:
- name: source

params:
  STATUS_TESTING_ACCESS_KEY_ID:
  STATUS_TESTING_SECRET_ACCESS_KEY:
  STATUS_TESTING_BUCKET:
  STATUS_TESTING_REGION:
